<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MultiTickettSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('multi_tickets')->insert([
            'trip_id'=>1,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>1,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>1,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>1,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //______
        DB::table('multi_tickets')->insert([
            'trip_id'=>2,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>2,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>2,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>2,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //_________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>3,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>3,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>3,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>3,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //_____________
        DB::table('multi_tickets')->insert([
            'trip_id'=>4,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>4,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>4,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>4,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //____________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>5,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>5,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>5,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>5,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //______________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>6,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>6,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>6,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>6,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //_________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>7,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>7,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>7,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>7,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //_____________
        DB::table('multi_tickets')->insert([
            'trip_id'=>8,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>8,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>8,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>8,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //_________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>9,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>9,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>9,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>9,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //_____________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>10,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>10,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>10,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>10,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //________________________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>11,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>11,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>11,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>11,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //______________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>12,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>12,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>12,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>12,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //_________________________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>13,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>13,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>13,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>13,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //______________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>14,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>14,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>14,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>14,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //__________________________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>15,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>15,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>15,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>15,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //__________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>16,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>16,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>16,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>16,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>17,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>17,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>17,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>17,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //__________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>18,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>18,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>18,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>18,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //_____________
        DB::table('multi_tickets')->insert([
            'trip_id'=>19,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>19,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>19,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>19,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //_______________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>20,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>20,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>20,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>20,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //__________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>21,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>21,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>21,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>21,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //___________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>22,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>22,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>22,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>22,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //___________
        DB::table('multi_tickets')->insert([
            'trip_id'=>23,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>23,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>23,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>23,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //_______________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>24,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>24,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>24,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>24,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //___________________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>25,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>25,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>25,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>25,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //_______________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>26,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>26,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>26,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>26,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //____________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>27,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>27,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>27,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>27,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //__________________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>28,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>28,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>28,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>28,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //___________________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>29,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>29,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>29,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>29,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //____________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>30,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>30,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>30,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>30,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //____________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>31,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>31,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>31,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>31,
            'type'=>'Economy_class',
            'price'=>400
        ]);
        //____________________________
        DB::table('multi_tickets')->insert([
            'trip_id'=>32,
            'type'=>'First_class',
            'price'=>1200
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>32,
            'type'=>'Business_class',
            'price'=>1000
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>32,
            'type'=>'Premium_Economy_class',
            'price'=>700
        ]);
        DB::table('multi_tickets')->insert([
            'trip_id'=>32,
            'type'=>'Economy_class',
            'price'=>400
        ]);
    }
}
