<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SingleTicketSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('single_tickets')->insert([
            'trip_id'=>1,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>1,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>1,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>1,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //______
        DB::table('single_tickets')->insert([
            'trip_id'=>2,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>2,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>2,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>2,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //_________________
        DB::table('single_tickets')->insert([
            'trip_id'=>3,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>3,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>3,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>3,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //_____________
        DB::table('single_tickets')->insert([
            'trip_id'=>4,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>4,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>4,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>4,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________
        DB::table('single_tickets')->insert([
            'trip_id'=>5,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>5,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>5,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>5,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //______________________
        DB::table('single_tickets')->insert([
            'trip_id'=>6,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>6,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>6,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>6,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //_________________
        DB::table('single_tickets')->insert([
            'trip_id'=>7,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>7,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>7,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>7,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //_____________
        DB::table('single_tickets')->insert([
            'trip_id'=>8,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>8,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>8,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>8,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //_________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>9,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>9,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>9,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>9,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //_____________________
        DB::table('single_tickets')->insert([
            'trip_id'=>10,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>10,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>10,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>10,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //________________________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>11,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>11,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>11,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>11,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //______________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>12,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>12,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>12,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>12,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //_________________________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>13,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>13,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>13,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>13,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //______________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>14,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>14,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>14,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>14,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //__________________________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>15,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>15,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>15,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>15,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //__________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>16,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>16,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>16,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>16,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>17,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>17,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>17,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>17,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //__________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>18,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>18,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>18,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>18,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //_____________
        DB::table('single_tickets')->insert([
        'trip_id'=>19,
        'type'=>'First_class',
        'price'=>600
    ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>19,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>19,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>19,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //_______________________
        DB::table('single_tickets')->insert([
            'trip_id'=>20,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>20,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>20,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>20,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //__________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>21,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>21,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>21,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>21,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //___________________
        DB::table('single_tickets')->insert([
            'trip_id'=>22,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>22,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>22,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>22,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //___________
        DB::table('single_tickets')->insert([
            'trip_id'=>23,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>23,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>23,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>23,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //_______________________
        DB::table('single_tickets')->insert([
            'trip_id'=>24,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>24,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>24,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>24,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //___________________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>25,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>25,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>25,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>25,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //_______________________
        DB::table('single_tickets')->insert([
            'trip_id'=>26,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>26,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>26,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>26,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________
        DB::table('single_tickets')->insert([
            'trip_id'=>27,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>27,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>27,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>27,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //__________________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>28,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>28,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>28,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>28,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //___________________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>29,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>29,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>29,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>29,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>30,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>30,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>30,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>30,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>31,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>31,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>31,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>31,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>32,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>32,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>32,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>32,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>33,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>33,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>33,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>33,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>34,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>34,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>34,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>34,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>35,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>35,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>35,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>35,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>36,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>36,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>36,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>36,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>37,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>37,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>37,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>37,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>38,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>38,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>38,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>38,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>39,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>39,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>39,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>39,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>40,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>40,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>40,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>40,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>41,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>41,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>41,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>41,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>42,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>42,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>42,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>42,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>43,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>43,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>43,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>43,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>44,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>44,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>44,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>44,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>45,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>45,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>45,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>45,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>46,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>46,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>46,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>46,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>47,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>47,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>47,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>47,
            'type'=>'Economy_class',
            'price'=>200
        ]);
        //____________________________
        DB::table('single_tickets')->insert([
            'trip_id'=>48,
            'type'=>'First_class',
            'price'=>600
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>48,
            'type'=>'Business_class',
            'price'=>500
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>48,
            'type'=>'Premium_Economy_class',
            'price'=>300
        ]);
        DB::table('single_tickets')->insert([
            'trip_id'=>48,
            'type'=>'Economy_class',
            'price'=>200
        ]);
    }
}
